source 'https://rubygems.org'

# This workaround was generated by Rails itself. For more info, see:
# https://stackoverflow.com/a/41454572/6763239
git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?("/")
  "https://github.com/#{repo_name}.git"
end

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 5.1.3'

# NOTE: This app does not yet require a database. When it does, we should use postgres.
# Use sqlite3 as the database for Active Record
# Leaving this in since here since I think it's simpler than trying to remove it
# after-the-fact and then readd it in the future. On that topic, see:
# https://stackoverflow.com/a/6579055/6763239
# https://stackoverflow.com/a/26065959/6763239
gem 'sqlite3'

# Use Puma as the app server
# Version 3.10.0+ for this issue: https://github.com/seuros/capistrano-puma/issues/237
gem 'puma', '>= 3.10.0', group: [:production, :staging, :virtualbox]

# Asset Stuff.
gem 'sass-rails', '~> 5.0'
gem 'bootstrap-sass', '~> 3.3.6'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Turbolinks makes navigating your web application faster. Read more: https://github.com/turbolinks/turbolinks
gem 'turbolinks', '~> 5'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.5'
gem 'jquery-rails'

# We do not use CoffeeScript.
# Use CoffeeScript for .coffee assets and views
# gem 'coffee-rails', '~> 4.2'

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
  # Adds support for Capybara system testing and selenium driver
  gem 'capybara', '~> 2.13'
  gem 'selenium-webdriver'
end

group :development do
  # Access an IRB console on exception pages or by using <%= console %> anywhere in the code.
  gem 'web-console', '>= 3.3.0'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end

gem 'listen', '>= 3.0.5', '< 3.2'

# Deployment
group :development do
  gem "capistrano", '~>3.7'
  gem 'capistrano-rails', '~> 1.3'
  gem 'capistrano-rbenv'
  gem 'capistrano3-puma'
end

gem 'rubocop'

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
