---
- name: Install nginx repo rpm
  become: true
  yum:
    name: http://nginx.org/packages/centos/7/noarch/RPMS/nginx-release-centos-7-0.el7.ngx.noarch.rpm

- name: Install nginx
  become: true
  yum:
    name: nginx
    state: latest

- name: Create nginx directories
  become: true
  file:
    state: directory
    path: "{{ nginx_path}}/{{ item }}"
  with_items: "{{ nginx_dirs }}"

- name: Create available server block files
  become: true
  template:
    src: "{{ item }}.conf.j2"
    dest: "{{ nginx_path }}/sites-available/{{ item }}.conf"
  with_items: "{{ sites_available }}"

- name: Create symlinks for enabled server block files
  become: true
  file:
    src: "{{ nginx_path }}/sites-available/{{ item }}.conf"
    dest: "{{ nginx_path }}/sites-enabled/{{ item }}.conf"
    state: link
  with_items: "{{ sites_enabled }}"

- name: Create nginx conf
  become: true
  template:
    src: nginx.conf.j2
    dest: "{{ nginx_path }}/nginx.conf"
  notify: Reload nginx

- name: Start nginx service
  become: true
  service:
    name: nginx
    state: started
    enabled: yes