---
- name: Generate RSA key
  become: true
  openssl_privatekey:
    path: "{{ ssl_private_key }}"
    size: 2048
    type: RSA

- name: Set RSA key permissions
  become: true
  file:
    path: "{{ ssl_private_key }}"
    state: touch
    owner: root
    mode: 700

- name: Generate CSR
  become: true
  command: >
    openssl req -new -sha256
    -subj "{{ ssl_crt_fields }}"
    -key {{ ssl_private_key }}
    -out {{ ssl_csr}}
    creates={{ ssl_csr}}

- name: Generate self-signed SSL certificate
  become: true
  command: >
    openssl req -x509 -nodes -days 365
    -in {{ ssl_csr}}
    -key {{ ssl_private_key }}
    -out {{ ssl_crt}}
    creates={{ ssl_crt }}

- name: Generate DH param
  become: true
  command: >
    openssl dhparam -out {{ ssl_dhparam }} 2048
    creates={{ ssl_dhparam }}