- hosts: webserver
  remote_user: wimops

  vars_files:
    - vars/defaults.yml
    - vars/{{ inventory_hostname }}-defaults.yml

  roles:
    - role: common
    - role: ssl
    - role: nginx
    - role: ruby
    - role: logs
    - role: deployment
    - role: ssh