#
# Common tasks for provisioning a new Red Hat server.
#
---
- name: "Install required Yum packages."
  yum: name={{ item }} state=latest
  with_items:
    - python
    - python-setuptools
    - python-setuptools-devel
    - logrotate

- name: "Install pip with easy_install."
  easy_install: name=pip state=latest

- name: "Install required Python packages."
  pip: name={{ item }}
  with_items:
    - pyopenssl

# This is required for the rbenv role. CentOS is ok but Red Hat requires extra repo.
# See https://github.com/zzet/ansible-rbenv-role/issues/109
- debug:
    msg: "Ansible distribution is {{ ansible_distribution }}"
- name: "Enable extra Red Hat repositories with required packages."
  shell: yum-config-manager --enable rhel-7-server-optional-rpms
  when: ansible_distribution == 'RedHat'
