---
#rbenv
rbenv_root_path: /usr/local/rbenv
rbenv_src: https://github.com/rbenv/rbenv.git

rbenv_dependencies:
  - gcc-c++
  - bzip2
  - openssl-devel
  - libyaml-devel
  - libffi-devel
  - postgresql-devel
  - sqlite-devel
  - readline-devel
  - zlib-devel
  - gdbm-devel
  - ncurses-devel
  - git

rbenv_directories:
  - versions
  - shims
  - plugins

#ruby
ruby_build_repo: https://github.com/rbenv/ruby-build.git
ruby_version: 2.4.0