---
deploy_path: "{{ remote_app_root_path }}"
deploy_usr: deploy
deploy_usr_dir: /home/{{ deploy_usr }}
deploy_usr_ssh_path: "{{ deploy_usr_dir }}/.ssh"
deploy_usr_pw_path: "/home/{{ dev_usr }}/.pw-deploy"

capistrano_dir_paths:
  - "{{ remote_app_root_path }}/shared"
  - "{{ remote_app_root_path }}/releases"
  - "{{ remote_app_root_path }}/repo"